service: aws-node
frameworkVersion: "4.4.11"

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-webpack
  # - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: ${opt:region, 'ap-south-1'}
  stage: ${opt:stage, 'dev'}
  stackName: ${self:service}-${self:provider.stage}-stack
  timeout: 45
  memorySize: 640

package:
  individually: true
  patterns:
    - "!./**"

custom:
  default: ${file(./config/default.yml)}
  prune:
    automatic: true
    number: 1
  webpack:
    webpackConfig: webpack.config.js

build:
  esbuild: false

functions:
  lambdaOne:
    name: ${self:service}-lambdaOne-${self:provider.stage}
    description: "Lambda function for lambdaOne"
    handler: src/lambdaOne/index.handler
    environment:
      ENV: ${self:provider.stage}
      LOG_LEVEL: ${self:custom.default.environments.${self:provider.stage}.LOG_LEVEL}
      LOG_FORMAT: ${self:custom.default.environments.${self:provider.stage}.LOG_FORMAT}
    package:
      patterns:
        - src/lambdaOne/**
        - src/utils/**

  lambdaTwo:
    name: ${self:service}-lambdaTwo-${self:provider.stage}
    description: "Lambda function for lambdaTwo"
    handler: src/lambdaTwo/index.handler
    environment:
      ENV: ${self:provider.stage}
      LOG_LEVEL: ${self:custom.default.environments.${self:provider.stage}.LOG_LEVEL}
      LOG_FORMAT: ${self:custom.default.environments.${self:provider.stage}.LOG_FORMAT}
    package:
      patterns:
        - src/lambdaTwo/**
        - src/utils/**
