resources:
  Resources:
    AppSyncRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.base}-appsync-cloudwatch-logs-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - appsync.amazonaws.com
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.base}-appsync-comprehensive-access-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                # CloudWatch Logs Permissions
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogGroups
                    - logs:DescribeLogStreams
                  Resource:
                    - arn:aws:logs:${self:provider.region}:${aws:accountId}:log-group:/aws/appsync/${self:appSync.name}:*

                # Lambda Invocation Permissions
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                    - lambda:GetFunction
                  Resource:
                    - arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:${self:custom.base}*

                # DynamoDB Permissions
                - Effect: Allow
                  Action:
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                    - dynamodb:DescribeTable
                  Resource:
                    - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.base}*

                # S3 Permissions
                - Effect: Allow
                  Action:
                    - s3:GetObject
                    - s3:PutObject
                    - s3:ListBucket
                    - s3:DeleteObject
                    - s3:GetBucketLocation
                  Resource:
                    - arn:aws:s3:::${self:custom.base}*
                    - arn:aws:s3:::${self:custom.base}*/*

                # Optional: Allow IAM pass role for Lambda
                - Effect: Allow
                  Action:
                    - iam:PassRole
                  Resource:
                    - arn:aws:iam::${aws:accountId}:role/${self:custom.base}*
